### ISSUE TITLE
Generated filenames should be unique

### ISSUE THREAD

**Issue by peter-tomaselli** [wayfair/kombucha#5]
Right now, REST snapshots are written to a filename determined by their path, and GraphQL snapshots are written to a filename determined by the hash of their query text. In both cases, this is not unique enough: it’s possible to write a config file that tests two different REST requests that happen to have the same path (this may even be desirable, for some kinds of tests).

Likewise, it’s possible to write a config file that tests two different GraphQL requests that happen to have the same query text. 

We should fix this so that every snapshot gets a unique filename. The filename must be “stable” even if surrounding tests are added, removed, or modified (for example, a simple sequence number won’t work). 

We should do this ASAP since it will be a breaking change with respect to users of Kombucha: their current snapshots will not be usable (unless they perform a lot of laborious renaming) after this fix since the filename generation code will have changed.

**Comment by simonpierreroy1** [comment]
Was all fixed in the PR #6.
